import { memo, useCallback, useState } from 'react';
import { safeLocalStorageGet, safeLocalStorageSet } from '../utils/helpers';
import { Icons } from './icons';

/**
 * First-use disclosure for the AI assistant.
 *
 * Two things have to be true before an AI feature is honest with its users: they
 * must know a model is involved, and they must know their note content leaves the
 * device. Neither was stated anywhere in the UI, so a user could paste
 * confidential text into a note and have it sent to a third-party model with no
 * notice at all.
 *
 * The notice also carries the accuracy caveat, which is the other half of setting
 * a correct expectation: output can be wrong, and inserting it into a note is the
 * user's decision, not the assistant's.
 */

const DISMISS_KEY = 'noteflow-ai-disclosure-dismissed';

export const AiDisclosure = memo(function AiDisclosure({ providerLabel }: { providerLabel: string }) {
  const [dismissed, setDismissed] = useState<boolean>(
    () => safeLocalStorageGet<boolean>(DISMISS_KEY, false) === true
  );

  const dismiss = useCallback(() => {
    safeLocalStorageSet(DISMISS_KEY, true);
    setDismissed(true);
  }, []);

  if (dismissed) return null;

  return (
    <div
      role="note"
      className="flex items-start gap-2 px-4 py-2.5 border-b border-border dark:border-white/5 bg-amber-50 dark:bg-amber-500/10 flex-shrink-0"
    >
      <span aria-hidden className="text-sm leading-none mt-0.5">
        ⚠️
      </span>
      <p className="flex-1 text-[11px] leading-snug text-amber-900 dark:text-amber-200/90">
        Responses are generated by AI and may be inaccurate or invent details —
        review before you keep them. Your note content is sent to {providerLabel} to
        produce a reply.
      </p>
      <button
        type="button"
        onClick={dismiss}
        aria-label="Dismiss AI notice"
        className="p-1 rounded-lg text-amber-900/60 dark:text-amber-200/60 hover:text-amber-900 dark:hover:text-amber-200 hover:bg-amber-900/10 dark:hover:bg-amber-200/10 transition-colors flex-shrink-0"
      >
        <Icons.Close className="w-3.5 h-3.5" />
      </button>
    </div>
  );
});
